### ISSUE TITLE
The map is randomly littered with invisible portals that teleport units

### ISSUE THREAD

**Issue by XHawk87** [longturn/rules-of-chaos#12]
- Portals will be unidirectional. You can travel through it to a destination, but you can't travel back the same way.
- Portals will remain open for a random number of turns after which they disappear.
- An initial number of portals will be spawned at game start with a wide spread of durations.
- New portals randomly appear over time, approximately balancing out portals disappearing due to age.

**Comment by lmoureaux** [comment]
Do the portals teleport to the same place every time? Do they work both ways?

**Comment by XHawk87** [comment]
I quite like the idea of units getting stranded out in the middle of nowhere, so I'd say one-way. I think having them open for a random amount of time before they close and another opens up elsewhere might be interesting. That way you can take advantage of a useful portal, but only if you act quickly, and you can't assume that any tile is safe.
